[package]
name = "cds210_proj"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
linfa = "0.6.1"
linfa-trees = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
csv = "1.2"
